services:
  frontend:
    image: hanuman97/tracking-hub-frontend:latest
    container_name: tracking-hub-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/ec2-user/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /home/ec2-user/privkey.pem:/etc/ssl/private/privkey.pem:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
